steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/veda-analytics-api", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/veda-analytics-api"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "veda-analytics-api",
        "--image",
        "gcr.io/$PROJECT_ID/veda-analytics-api",
        "--region",
        "australia-southeast1",
      ]
images:
  - gcr.io/$PROJECT_ID/veda-analytics-api
