name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Forrmat & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Git | Checkout
        uses: actions/checkout@v4

      - name: BiomeJS | Setup
        uses: biomejs/setup-biome@v2
      
      - name: BiomeJS | Forrmat & Lint
        run: biome ci .

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git | Checkout
        uses: actions/checkout@v4

      - name: Docker | Setup
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: VeDA/be-analytics-api:latest